//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CINTScore
    {
        public int ID { get; set; }
        public string ePROMsType { get; set; }
        public string IDName { get; set; }
        public string IDValue { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string PostCode { get; set; }
        public string Score { get; set; }
        public string SurveyMonkeyID { get; set; }
        public string RespondedID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
