//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientSurvey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientSurvey()
        {
            this.PatientSuggestions = new HashSet<PatientSuggestion>();
            this.PatientSurveyStatus = new HashSet<PatientSurveyStatu>();
            this.ProviderPatientThirdPartyApps = new HashSet<ProviderPatientThirdPartyApp>();
            this.PatientSurvey_Pathway_PatientSurveyStatus = new HashSet<PatientSurvey_Pathway_PatientSurveyStatus>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PatientID { get; set; }
        public Nullable<int> SurveyID { get; set; }
        public Nullable<System.Guid> OrganizationID { get; set; }
        public Nullable<System.Guid> PracticeID { get; set; }
        public Nullable<System.Guid> ProviderID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsSend { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientSuggestion> PatientSuggestions { get; set; }
        public virtual Practice Practice { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Survey Survey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientSurveyStatu> PatientSurveyStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderPatientThirdPartyApp> ProviderPatientThirdPartyApps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientSurvey_Pathway_PatientSurveyStatus> PatientSurvey_Pathway_PatientSurveyStatus { get; set; }
    }
}
