//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientSurveyStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientSurveyStatu()
        {
            this.PatientSurvey_Pathway_PatientSurveyStatus = new HashSet<PatientSurvey_Pathway_PatientSurveyStatus>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PatientSurveyID { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Score { get; set; }
    
        public virtual PatientSurvey PatientSurvey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientSurvey_Pathway_PatientSurveyStatus> PatientSurvey_Pathway_PatientSurveyStatus { get; set; }
    }
}
