//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientSurvey_Pathway_PatientSurveyStatus
    {
        public System.Guid ID { get; set; }
        public System.Guid PatientSurveyID { get; set; }
        public System.Guid PathwayID { get; set; }
        public Nullable<System.Guid> PatientSurveyStatusID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
    
        public virtual Pathway Pathway { get; set; }
        public virtual PatientSurvey PatientSurvey { get; set; }
        public virtual PatientSurveyStatu PatientSurveyStatu { get; set; }
    }
}
