//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider()
        {
            this.PatientProviders = new HashSet<PatientProvider>();
            this.PatientSurveys = new HashSet<PatientSurvey>();
            this.ProviderOrganizations = new HashSet<ProviderOrganization>();
            this.ProviderPatientThirdPartyApps = new HashSet<ProviderPatientThirdPartyApp>();
            this.ProviderPractices = new HashSet<ProviderPractice>();
            this.ProviderTerms = new HashSet<ProviderTerm>();
            this.UserSurveys = new HashSet<UserSurvey>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string Code { get; set; }
        public Nullable<short> ProviderTypeID { get; set; }
        public Nullable<int> SalutationID { get; set; }
        public string MedicareProviderNumber { get; set; }
        public string HealthProviderIdentifier { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<long> AddressID { get; set; }
        public string PHN { get; set; }
        public string LHD { get; set; }
        public string LHN { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual Contact Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientProvider> PatientProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientSurvey> PatientSurveys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderOrganization> ProviderOrganizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderPatientThirdPartyApp> ProviderPatientThirdPartyApps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderPractice> ProviderPractices { get; set; }
        public virtual ProviderType ProviderType { get; set; }
        public virtual Salutation Salutation { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderTerm> ProviderTerms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSurvey> UserSurveys { get; set; }
    }
}
