//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderPatientThirdPartyApp
    {
        public int ID { get; set; }
        public Nullable<int> ThirdPartyAppID { get; set; }
        public Nullable<System.Guid> ProviderID { get; set; }
        public Nullable<System.Guid> PatientSurveyID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedBy { get; set; }
    
        public virtual PatientSurvey PatientSurvey { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ThirdPartyApp ThirdPartyApp { get; set; }
    }
}
