//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderPractice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProviderPractice()
        {
            this.ProviderPracticeRoles = new HashSet<ProviderPracticeRole>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProviderId { get; set; }
        public Nullable<System.Guid> PracticeId { get; set; }
        public Nullable<System.Guid> ProviderOrganizationId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual Practice Practice { get; set; }
        public virtual ProviderOrganization ProviderOrganization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderPracticeRole> ProviderPracticeRoles { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
