//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderPracticeRole
    {
        public int ID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<System.Guid> ProviderPracticeID { get; set; }
    
        public virtual PracticeRole PracticeRole { get; set; }
        public virtual ProviderPractice ProviderPractice { get; set; }
    }
}
