//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShEhrDbEntities : DbContext
    {
        public ShEhrDbEntities()
            : base("name=ShEhrDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetConsumerDetail_Result> GetConsumerDetail(string iHINumber)
        {
            var iHINumberParameter = iHINumber != null ?
                new ObjectParameter("IHINumber", iHINumber) :
                new ObjectParameter("IHINumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetConsumerDetail_Result>("GetConsumerDetail", iHINumberParameter);
        }
    
        public virtual ObjectResult<GetConsumerDetailAddr_Result> GetConsumerDetailAddr(Nullable<int> contactID)
        {
            var contactIDParameter = contactID.HasValue ?
                new ObjectParameter("ContactID", contactID) :
                new ObjectParameter("ContactID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetConsumerDetailAddr_Result>("GetConsumerDetailAddr", contactIDParameter);
        }
    }
}
