//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Survey()
        {
            this.PatientSurveys = new HashSet<PatientSurvey>();
            this.UserSurveys = new HashSet<UserSurvey>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string ExternalTitle { get; set; }
        public string ExternalID { get; set; }
        public string CollectorID { get; set; }
        public string URL { get; set; }
        public string ContentCode { get; set; }
        public Nullable<System.Guid> CreatedByUserID { get; set; }
        public Nullable<short> SurveyCategoryID { get; set; }
        public Nullable<short> SurveySubCategoryID { get; set; }
        public Nullable<short> SurveyTypeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Language { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<decimal> NormValue { get; set; }
        public Nullable<int> Days { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientSurvey> PatientSurveys { get; set; }
        public virtual SurveyCategory SurveyCategory { get; set; }
        public virtual SurveyCategory SurveyCategory1 { get; set; }
        public virtual SurveyType SurveyType { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSurvey> UserSurveys { get; set; }
    }
}
