//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProperty
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid PropertyID { get; set; }
        public string Value { get; set; }
        public Nullable<short> DisplayOrder { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
