//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSecretQuestion
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public short SecretQuestionID { get; set; }
        public string OtherQuestion { get; set; }
        public string Answer { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual SecretQuestion SecretQuestion { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
